[General]
TcpServerPort=5760

[UdpEndpoint WFB-input]
Mode=server
Address=0.0.0.0
Port=14560

[UdpEndpoint QGC]
Mode=normal
Address=10.5.6.50
Port=14550

[UdpEndpoint tracker]
Mode=normal
Address=127.0.0.1
Port=14551
